services:
  majo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: majo
    ports:
      - "18789:18789"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx2g -Xms512m
