CREATE TABLE IF NOT EXISTS token_usage (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usage_date     VARCHAR(10)  NOT NULL,
    provider_id    VARCHAR(64)  NOT NULL DEFAULT '',
    model          VARCHAR(128) NOT NULL,
    prompt_tokens  INT          NOT NULL DEFAULT 0,
    completion_tokens INT NOT NULL DEFAULT 0,
    call_count     INT          NOT NULL DEFAULT 1,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
