ALTER TABLE settings ADD COLUMN IF NOT EXISTS heartbeat_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS heartbeat_every VARCHAR(16) NOT NULL DEFAULT '6h';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS heartbeat_target VARCHAR(64) NOT NULL DEFAULT 'main';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS heartbeat_timeout_seconds INT NOT NULL DEFAULT 120;
