-- Turn-level token usage (ADR-0011): one row per completed agent turn,
-- complementing the daily aggregate in token_usage (which stays unchanged).
CREATE TABLE IF NOT EXISTS token_usage_turns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id          VARCHAR(64)  NOT NULL DEFAULT 'default',
    chat_id           VARCHAR(64)  NULL,
    provider_id       VARCHAR(64)  NOT NULL DEFAULT '',
    model             VARCHAR(128) NOT NULL DEFAULT '',
    input_tokens      INT          NOT NULL DEFAULT 0,
    output_tokens     INT          NOT NULL DEFAULT 0,
    duration_ms       BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_token_usage_turns_agent_time
    ON token_usage_turns (agent_id, created_at);
