ALTER TABLE chats ADD COLUMN IF NOT EXISTS session_id VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE chats ADD COLUMN IF NOT EXISTS user_id VARCHAR(64) NOT NULL DEFAULT 'default';
ALTER TABLE chats ADD COLUMN IF NOT EXISTS channel VARCHAR(64) NOT NULL DEFAULT 'console';
ALTER TABLE chats ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP;
