CREATE TABLE IF NOT EXISTS active_models (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope         VARCHAR(16)  NOT NULL DEFAULT 'global',
    agent_id      VARCHAR(64)  NULL,
    provider_id   VARCHAR(64)  NOT NULL DEFAULT '',
    model_id      VARCHAR(128) NOT NULL DEFAULT '',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (scope, agent_id)
);

-- Global sentinel: empty/null agent_id for scope='global'
INSERT INTO active_models (scope, agent_id, provider_id, model_id)
SELECT 'global', NULL, '', ''
WHERE NOT EXISTS (
    SELECT 1 FROM active_models WHERE scope = 'global' AND agent_id IS NULL
);
