package com.agent.coding.service;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.Status;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.diff.DiffEntry;
import org.eclipse.jgit.lib.Constants;
import org.eclipse.jgit.lib.ObjectId;
import org.eclipse.jgit.lib.Repository;
import org.eclipse.jgit.revwalk.RevCommit;
import org.eclipse.jgit.revwalk.RevWalk;
import org.eclipse.jgit.storage.file.FileRepositoryBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Git workspace operations for the {@code /workspace/git/*} endpoints, ported
 * from qwenpaw app/routers/git.py. Uses JGit (already a project dependency);
 * no external git binary required.
 *
 * <p>Mirrors the qwenpaw behavior of auto-initialising a repository (with a
 * default .gitignore and an empty initial commit) the first time the
 * workspace is opened.
 */
@Service
public class GitService {

    private static final Logger log = LoggerFactory.getLogger(GitService.class);

    private static final String DEFAULT_GITIGNORE = """
            # Auto-generated by Majo Coding Mode

            # Python artefacts
            __pycache__/
            *.py[cod]
            *.egg-info/
            .venv/
            venv/
            env/
            .env

            # JS / build artefacts
            node_modules/
            dist/
            build/

            # OS
            .DS_Store

            # Majo runtime / internal directories
            data/
            sessions/
            missions/
            memory/
            browser/
            backup/
            skills/
            *.lock
            """;

    // ── repository resolution ──────────────────────────────────────────

    private Repository openRepo(Path dir) throws IOException {
        FileRepositoryBuilder builder = new FileRepositoryBuilder().findGitDir(dir.toFile());
        if (builder.getGitDir() == null) {
            throw new IOException("Not a git repository: " + dir);
        }
        return builder.build();
    }

    private boolean isOwnRepo(Path dir) {
        try {
            FileRepositoryBuilder builder = new FileRepositoryBuilder().findGitDir(dir.toFile());
            if (builder.getGitDir() == null) {
                return false;
            }
            Path gitDir = builder.getGitDir().toPath().toAbsolutePath().normalize();
            return gitDir.equals(dir.resolve(".git").toAbsolutePath().normalize());
        } catch (Exception e) {
            return false;
        }
    }

    /** Resolve the workspace dir, auto-initialising a repo if missing. */
    public Path ensureRepo(Path dir) throws IOException {
        if (!isOwnRepo(dir)) {
            initRepo(dir);
        }
        return dir;
    }

    private void initRepo(Path dir) throws IOException {
        try (Git git = Git.init().setDirectory(dir.toFile()).call()) {
            Path gitignore = dir.resolve(".gitignore");
            if (!Files.isRegularFile(gitignore)) {
                Files.writeString(gitignore, DEFAULT_GITIGNORE, StandardCharsets.UTF_8);
            }
            try {
                git.add().addFilepattern(".").call();
            } catch (GitAPIException ignored) {
                // Partial adds are fine for the initial commit.
            }
            git.commit()
                    .setAuthor("Majo", "majo@localhost")
                    .setMessage("Initial commit")
                    .setAllowEmpty(true)
                    .call();
        } catch (GitAPIException e) {
            throw new IOException("git init failed: " + e.getMessage(), e);
        }
        log.info("Initialised git repo in {}", dir);
    }

    private String branchName(Repository repo) throws IOException {
        String branch = repo.getBranch();
        return branch == null || branch.isBlank() ? "HEAD" : branch;
    }

    // ── status ─────────────────────────────────────────────────────────

    public Map<String, Object> status(Path dir) throws IOException, GitAPIException {
        ensureRepo(dir);
        try (Repository repo = openRepo(dir); Git git = new Git(repo)) {
            Status st = git.status().call();
            List<Map<String, Object>> changes = new ArrayList<>();
            for (String f : st.getAdded()) changes.add(change(f, "A", true));
            for (String f : st.getChanged()) changes.add(change(f, "M", true));
            for (String f : st.getRemoved()) changes.add(change(f, "D", true));
            for (String f : st.getModified()) changes.add(change(f, "M", false));
            for (String f : st.getMissing()) changes.add(change(f, "D", false));
            for (String f : st.getUntracked()) changes.add(change(f, "?", false));

            Map<String, Object> result = new LinkedHashMap<>();
            result.put("branch", branchName(repo));
            result.put("changes", changes);
            result.put("ahead", 0);
            result.put("behind", 0);
            return result;
        }
    }

    private static Map<String, Object> change(String path, String status, boolean staged) {
        Map<String, Object> c = new LinkedHashMap<>();
        c.put("path", path);
        c.put("status", status);
        c.put("staged", staged);
        return c;
    }

    // ── branches ───────────────────────────────────────────────────────

    public List<Map<String, Object>> branches(Path dir) throws IOException, GitAPIException {
        try (Repository repo = openRepo(dir); Git git = new Git(repo)) {
            String current = branchName(repo);
            List<Map<String, Object>> result = new ArrayList<>();
            for (org.eclipse.jgit.lib.Ref ref : git.branchList().call()) {
                String name = ref.getName().replace(Constants.R_HEADS, "");
                Map<String, Object> b = new LinkedHashMap<>();
                b.put("name", name);
                b.put("current", name.equals(current));
                b.put("remote", false);
                result.add(b);
            }
            return result;
        }
    }

    // ── checkout ───────────────────────────────────────────────────────

    public Map<String, Object> checkout(Path dir, String branch, boolean create)
            throws IOException, GitAPIException {
        try (Git git = new Git(openRepo(dir))) {
            if (create) {
                git.checkout().setCreateBranch(true).setName(branch).call();
            } else {
                git.checkout().setName(branch).call();
            }
            return Map.of("branch", branch);
        }
    }

    // ── diff ───────────────────────────────────────────────────────────

    public Map<String, Object> diff(Path dir, String path, boolean staged, boolean untracked)
            throws IOException, GitAPIException {
        try (Repository repo = openRepo(dir); Git git = new Git(repo)) {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            if (untracked && path != null && !path.isBlank()) {
                java.nio.file.Path target = dir.resolve(path).normalize();
                if (!target.startsWith(dir.normalize()) || !Files.isRegularFile(target)) {
                    return Map.of("diff", "");
                }
                String content = Files.readString(target, StandardCharsets.UTF_8);
                return Map.of("diff", "diff --git a/" + path + " b/" + path + "\n"
                        + "new file mode 100644\n--- /dev/null\n+++ b/" + path + "\n"
                        + "@@ -0,0 +1," + content.lines().count() + " @@\n"
                        + content.lines().map(l -> "+" + l).reduce((a, b) -> a + "\n" + b)
                        .orElse("") + "\n");
            }
            if (staged) {
                git.diff().setCached(true).setOutputStream(out).call();
            } else {
                git.diff().setOutputStream(out).call();
            }
            return Map.of("diff", out.toString(StandardCharsets.UTF_8));
        }
    }

    // ── stage / unstage ────────────────────────────────────────────────

    public Map<String, Object> stage(Path dir, List<String> paths) throws IOException, GitAPIException {
        try (Git git = new Git(openRepo(dir))) {
            List<String> targets = (paths == null || paths.isEmpty()) ? List.of(".") : paths;
            for (String p : targets) {
                git.add().addFilepattern(p).call();
            }
            return Map.of("staged", targets);
        }
    }

    public Map<String, Object> unstage(Path dir, List<String> paths) throws IOException, GitAPIException {
        try (Git git = new Git(openRepo(dir))) {
            List<String> targets = (paths == null || paths.isEmpty()) ? List.of(".") : paths;
            for (String p : targets) {
                git.reset().addPath(p).call();
            }
            return Map.of("unstaged", targets);
        }
    }

    // ── commit ─────────────────────────────────────────────────────────

    public Map<String, Object> commit(Path dir, String message) throws IOException, GitAPIException {
        if (message == null || message.isBlank()) {
            throw new IllegalArgumentException("Commit message cannot be empty");
        }
        try (Git git = new Git(openRepo(dir))) {
            org.eclipse.jgit.lib.ObjectId head = git.commit().setMessage(message.trim()).call();
            return Map.of("committed", true, "output", head.name());
        }
    }

    // ── discard ─────────────────────────────────────────────────────────

    public Map<String, Object> discard(Path dir, List<String> paths) throws IOException, GitAPIException {
        try (Git git = new Git(openRepo(dir))) {
            List<String> targets = (paths == null || paths.isEmpty()) ? List.of(".") : paths;
            for (String p : targets) {
                git.checkout().addPath(p).call();
            }
            git.clean().setForce(true).setIgnore(false).setPaths(new java.util.LinkedHashSet<>(targets)).call();
            return Map.of("discarded", targets);
        }
    }

    // ── commit-diff ─────────────────────────────────────────────────────

    public Map<String, Object> commitDiff(Path dir, String hash) throws IOException, GitAPIException {
        try (Repository repo = openRepo(dir); RevWalk walk = new RevWalk(repo)) {
            ObjectId id = repo.resolve(hash);
            if (id == null) {
                throw new IllegalArgumentException("Unknown commit: " + hash);
            }
            RevCommit commit = walk.parseCommit(id);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            org.eclipse.jgit.treewalk.CanonicalTreeParser oldTree = new org.eclipse.jgit.treewalk.CanonicalTreeParser();
            org.eclipse.jgit.treewalk.CanonicalTreeParser newTree = new org.eclipse.jgit.treewalk.CanonicalTreeParser();
            try (org.eclipse.jgit.lib.ObjectReader reader = repo.newObjectReader()) {
                org.eclipse.jgit.revwalk.RevTree oldRevTree = commit.getParentCount() > 0
                        ? walk.parseTree(commit.getParent(0)) : null;
                oldTree.reset(reader, oldRevTree == null ? id : oldRevTree.getId());
                newTree.reset(reader, commit.getTree().getId());
            }
            try (Git git = new Git(repo)) {
                List<DiffEntry> entries = git.diff()
                        .setOutputStream(out)
                        .setOldTree(oldTree)
                        .setNewTree(newTree)
                        .call();
                String diff = out.toString(StandardCharsets.UTF_8);
                String stat = "diff --git " + hash + " (" + entries.size() + " files)\n";
                return Map.of("diff", stat + diff, "hash", hash);
            }
        }
    }

    // ── log ─────────────────────────────────────────────────────────────

    public List<Map<String, Object>> log(Path dir, int limit) throws IOException, GitAPIException {
        try (Repository repo = openRepo(dir); Git git = new Git(repo)) {
            int n = limit <= 0 ? 20 : Math.min(limit, 100);
            List<Map<String, Object>> commits = new ArrayList<>();
            for (RevCommit rev : git.log().setMaxCount(n).call()) {
                Map<String, Object> c = new LinkedHashMap<>();
                c.put("hash", rev.getName().substring(0, Math.min(8, rev.getName().length())));
                c.put("author", rev.getAuthorIdent().getName());
                c.put("date", rev.getAuthorIdent().getWhen().toInstant().toString().substring(0, 10));
                c.put("message", rev.getFullMessage().trim());
                commits.add(c);
            }
            return commits;
        }
    }
}
