server:
  port: 18789

spring:
  datasource:
    url: jdbc:h2:file:./data/majo/db/majo;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: MajoH2Pool
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate.connection.isolation: 2
      hibernate.connection.autocommit: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
  file:
    name: ./data/majo/majo.log

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
